### ISSUE TITLE
/routes proxy and cleanup 

### ISSUE THREAD

**Issue by exxonvaldez** [trynmaps/metrics-mvp#133]
As Jesse suggested in #132 :  For production, we should probably have nginx in front of flask to gzip and cache responses to reduce bandwidth and reduce load on the flask backend. Don't need to implement that now though.  Vickie H also suggests Envoy (https://www.loggly.com/blog/benchmarking-5-popular-load-balancers-nginx-haproxy-envoy-traefik-and-alb/)

Also, if the changes for #132 have no issues and can become permanent, then there is some refactoring and cleanup as described there.  Can clone this issue as desired for that.

**Comment by youngj** [comment]
We could also consider using a CDN like AWS Cloudfront or Cloudflare for caching and compression.
