### ISSUE TITLE
Improve route sorting

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#164]
Pretty small issue but I'll flag it nonetheless.

Currently the routes are sorted like 1, 10, 11, ... 19, 1AX, 1BX, 2, 20, 21, etc. Ideally it would be sorted like 1, 1AX, 1BX, 2, 3, ... 9, 10, 11, ... 20, 21, etc. That is, we should sort by route number, not lexically.

![Screenshot 2019-07-10 at 8 38 57 PM](https://user-images.githubusercontent.com/728084/61020469-c2103a80-a352-11e9-982b-dcecbdceeb4e.png)

**Comment by hathix** [comment]
This should be done in https://github.com/trynmaps/metrics-mvp/blob/master/frontend/src/components/RouteTable.jsx

**Comment by hathix** [comment]
basically, grab the sorting function from this stackoverflow answer: https://stackoverflow.com/a/8107614.

then in the `desc` sort function, if the `orderBy` happens to be the Name (and is a string), use that stackoverflow function instead. the current sorting function works great for numerical things but not these strings (and this string thing doesn't work for numerical values).

**Comment by exxonvaldez** [comment]
We could also order routes the same as they are in the route picker.  This order comes from the Nextbus API that lists all the routes.  If the `orderBy` is Name, just use routes array unsorted (and reversed if `order` is 'desc').
