### ISSUE TITLE
Show average # of bus runs/day for time periods

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#170]
When I filter a bus route's stats by time of day, I want to know how big the sample size is: is there just 1 bus that runs during this time period (which would make the data less reliable) or are there a bunch? It would be great to show the average number of buses that run during that time period.

In this example, I'm looking at what I believe is a night route; it says it works pretty well during the day but I'm not sure exactly how many of those buses run during the day in the first place.

![Screenshot 2019-07-10 at 9 07 56 PM](https://user-images.githubusercontent.com/728084/61021542-d35b4600-a356-11e9-8e10-f878d9743477.png)

**Comment by exxonvaldez** [comment]
If you scroll down, you can see the number of runs used for headway and trip time calculations for the given time period.  You can then determine the number of vehicles per hour.

What we don't have is something like a histogram that shows number of arrivals per hour, which would give a sense of when the route actually goes by a stop and doesn't.  It would also be great to know when the first/last bus for a stop actually is, that could be a hover on the histogram, or we could make the histogram more finely grained, like 15 minute blocks.

![Screen Shot 2019-08-02 at 12 21 27 AM](https://user-images.githubusercontent.com/44861283/62351862-939dff00-b4bb-11e9-999d-2919f4e95899.png)

**Comment by hathix** [comment]
I think we already have this solved, per terence's comment
