### ISSUE TITLE
Date picker component in isochrone map

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#184]
Currently there is only a dropdown with a hardcoded list of dates. Ideally we should be able to reuse our existing date picker component.

**Comment by exxonvaldez** [comment]
Once #222 is merged, if the common page header code is added (the blue app bar), then there will be a date picker available that sets the date in state.route.graphParams.date.

**Comment by youngj** [comment]
fixed in https://github.com/trynmaps/metrics-mvp/pull/226
