### ISSUE TITLE
Geolocation button in isochrone map

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#186]
It would be useful to automatically draw the isochrones starting at the user's current location, if known

**Comment by licarpen** [comment]
Working on this on branch geolocation-button.  Progress so far is generating the isochrones on initial page load if user has geolocation services enabled.  Is it necessary to add logic to catch the case when user's geolocation is outside of computable gray area?  Is it necessary to have a button?  It seems like a better user experience for the isochrones to generated on pageload instead of on a button click.  Thoughts?

**Comment by youngj** [comment]
Having the isochrones generated on the initial page load sounds good to me. To keep the experience consistent regardless of whether or not geolocation services are enabled or whether the user is in the service area, I'd propose using the user's location if it's available and within the service area; otherwise, using a coordinate of some central well-connected place as the default (like Pioneer Courthouse @ 45.51858,-122.67764 in Portland), or agency.initialMapCenter if no other coordinate is defined. The default coordinate could be defined in the js_properties section of the agency config in backend/agencies/*.yaml similarly to initialMapCenter.

For SF Muni, the service area is defined as GeoJSON in backend/agencies/muni.yaml , but for TriMet the service area has not been defined yet. I defined the SF Muni service area manually by drawing polygons in http://geojson.io/ and then exporting it. However, this may not be the best approach for defining service areas since it requires manual work for each agency and may not stay accurate over time. It would probably be better to check if the coordinate is within a certain radius (e.g. 1000 meters) of any coordinate of any route in the transit agency. Maybe that would be out of scope for this issue and could be a separate issue. 

An even simpler heuristic would be to use the user's location as the initial position if it is within the current viewport of the isochrone map, and otherwise use the default location from the agency config.

**Comment by licarpen** [comment]
I'm encountering some issues that are beyond my skillset at this point - when going directly to the /isochrone path, the isochrone generates with the user's lat/lng or default lat/lng as expected.  However, when navigating the the /isochrone from home, the warning below is generated.  Thoughts?
<img width="705" alt="Screen Shot 2020-03-12 at 9 57 19 PM" src="https://user-images.githubusercontent.com/48000707/76591332-49e3b100-64ad-11ea-89af-a8fae0c87823.png">

**Comment by youngj** [comment]
It looks like this warning is unrelated to the isochrones not being generated.

The issue is that when navigating to /isochrone from the home screen, this.props.routes is already set, so componentDidUpdate doesn't trigger and setInitialLocation isn't called.

To handle this case you can call setInitialLocation from componentDidMount if the routes are already loaded, e.g:

```
if (this.props.routes) {
   this.setInitialLocation();
}
```
