### ISSUE TITLE
Run a giant round of beautification

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#193]
Currently a lot of our PRs have a lot of unrelated code changes (that are just spacing/formatting) mixed in with the "real" changes. I think this is because some people have beautification hooks or their IDE does it automatically.

Can we have someone just run the beautifier on every file in the app, so that no future PRs get this problem?

**Comment by exxonvaldez** [comment]
The problem will reoccur unless we can also get the pre-commit hook working for all developers.

**Comment by hathix** [comment]
Arun has run several rounds; has 18 errors left to fix
