### ISSUE TITLE
Show the most recent date when 20 minute wait happens

### ISSUE THREAD

**Issue by leonsanbo** [trynmaps/metrics-mvp#194]
It could be useful to indicate at the 20 min wait line about the exact date when a long wait happens, plus how long it was. Also, it would be helpful to present the cause for the long wait (especially if it's by accident, like car crash, or trees falldown etc.) so that users may have a clearer idea on how to interpret the data and make decisions based on the information.

**Comment by hathix** [comment]
I don't think we can figure out what caused the long wait, but showing when it last happened (or how many times a day it happens, perhaps) would be good.
