### ISSUE TITLE
Make the trip info table look more like the RouteSummary component

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#200]
#176 made a great new component for the route summary:

![Screenshot 2019-07-24 at 7 21 38 PM](https://user-images.githubusercontent.com/728084/61841078-534dd980-ae48-11e9-96b5-93399f88be51.png)

But the trip info table is still pretty old-school:

![Screenshot 2019-07-24 at 7 21 50 PM](https://user-images.githubusercontent.com/728084/61841077-534dd980-ae48-11e9-913f-3bedd38e0bd0.png)

It would be good to make this one look more like the fancy RouteSummary component. (To be clear - it doesn't need to be a table! Just some good way to visualize the data).

**Comment by exxonvaldez** [comment]
Work in progress:

![Screen Shot 2019-09-13 at 11 03 01 AM](https://user-images.githubusercontent.com/44861283/64886426-0520af80-d61b-11e9-8a46-1bc99abb2395.png)
