### ISSUE TITLE
Add Material date picker

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#213]
#178 added a material timepicker. Let's add a material datepicker too; we don't currently have one that works. Looks at Uber Movement's UI and steal that, ideally.

**Comment by exxonvaldez** [comment]
Note: there is no core date picker, they just support native browser date pickers.  The Material UI docs point to an external implementation here:  https://material-ui-pickers.dev/demo/datepicker#inline-mode (looks ok, maybe a bit odd).  The Uber date picker looks custom to me, it is pretty slick.
