### ISSUE TITLE
Make sure router handles malformed input

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#216]
#211 added stateful routing, which is great. But it bugs out if you don't put arguments in the right order or type in, say, the wrong stop ID or a non-numerical stop ID. It should fail gracefully in these situations, and just pretend the malformed argument wasn't given at all.

**Comment by exxonvaldez** [comment]
Just noticed that we also get a crash when selecting "to stop" without a from stop.  Due to the way the routing regex works, the from stop id is parsed as "toStop", and then we call the graph ql api when we shouldn't.  @ckrajewski

**Comment by hathix** [comment]
* Make 404 go to homepage
* Throw away malformed elements of the URL and salvage as much as you can. E.g. <https://muni.opentransit.city/route/12/direction/12___I_F00/asdfasdfsadf/fromStop/6879> could become <https://muni.opentransit.city/route/12/direction/12___I_F00/> which is a valid URL.

**Comment by hathix** [comment]
OK, I think not many people are going to be mistyping the URLs. Instead just fix the 404 page. The current 404 page looks bad (it's just a single H3 on the entire page) but #607 at least puts it inside a shell with the header bar and all by default (all views get this treatment automatically). So a PR right now doesn't have to fix that, it should just improve the wording over "404".
