### ISSUE TITLE
Generate URL Path When Using Map or DropDowns

### ISSUE THREAD

**Issue by ckrajewski** [trynmaps/metrics-mvp#217]
Currently, no URL is generated when populating data through the use of the map or dropdowns.
As of PR #211 , we now support GET operations.
In order for users to share and use these URLs, we should auto-populate the URL parameters with the appropriate ids (i.e. /direction/14___O_F00) when selecting an inbound direction for route 14

**Comment by hathix** [comment]
To put it another way, the URL, the dropdowns, and the map should always be in sync. Whenever you, say, choose a stop or a direction in one, the others should all update to reflect that
