### ISSUE TITLE
Add support for "long wait probability" in dashboards

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#229]
@exxonvaldez had a metric that measures the probability that you have to wait 20+ minutes for a bus, called the "long wait probability." but we don't surface this information anywhere on the app. We should!

**Comment by jtanquil** [comment]
Should I make a PR that adds this probability to the wait times stats that the backend returns?

**Comment by exxonvaldez** [comment]
Yeah, that’s a good idea.  I’m thinking at the route level in the precomputed wait times?  We still have the long wait probability at the stop level.

**Comment by exxonvaldez** [comment]
Actually Jesse added route level precomputed wait files with the 20 min wait probability.  So this issue was fixed by #314.  Marking as closed.
