### ISSUE TITLE
Make the route page show a score of "--" when no data

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#233]
Currently the route page shows "0" for the score when there's no data. It should show "--" instead, like the other tiles.

![Screenshot 2019-08-07 at 6 54 49 PM](https://user-images.githubusercontent.com/728084/62669567-e9075f80-b944-11e9-9046-52cc6680a191.png)

**Comment by exxonvaldez** [comment]
Fixed by @youngj in #240.  Shows "--/100".
