### ISSUE TITLE
Make a Twitter bot that calls the daily summary API every day

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#253]
Part of the Twitter Bot project; [see the spec](https://docs.google.com/document/d/1e5How0CMhF-9PD2O3xUb3H3biUi-sBw2Z5EAIOQhKOk/edit#).

In #251, we will create an API that offers a daily summary of the Muni system.  We should also make a Twitter bot that calls that API every morning (~7am) and posts the paragraph output on Twitter.

I'm not sure if the code for that bot would go in this repo, but for the sake of keeping all our todos in one place, I'm putting it here.

**Comment by akgupta89** [comment]
Ideas:
- Report Card
- Weekly Best Line

**Comment by hathix** [comment]
This is being done in its own API https://github.com/trynmaps/opentransit-bot/pull/1
