### ISSUE TITLE
Refactor the codebase to pull out all SF-specific strings in constants files

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#254]
Part of the OT For Any City project; [see the spec](https://docs.google.com/document/d/1VoGpaReLsnudHk2LOR-BaGZAAb1p_jI1Le8cugpSj1U/edit#).

Basically, make it so that we could easily swap this to any other city with little more than some string changes.

**Comment by hathix** [comment]
Oh, interesting. It depends how much custom work is needed for each city- if there's a lot of custom code needed, that means forks are cleaner. But forks are harder to keep in sync. For now let's just tackle this issue and see what we learn about the difficulty of porting to a new city.

**Comment by TheLordHighExecutioner** [comment]
Is there an existing file that should pull these to, or should I make one?
