### ISSUE TITLE
Remove Direction input

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#264]
It's redundant to set the Direction and then the "From Stop" and "To Stop". Choosing a location from point A to B implies the direction, this would make input a lot more simpler entering locations like Google Maps.

**Comment by exxonvaldez** [comment]
Correction:  It's not the Transit app, it's the Routesy app in map mode that has you pick a stop to determine direction.  The Transit defaults to one direction and uses a carousel to let you pick another direction.

**Comment by hathix** [comment]
I think this is outdated, since we got rid of the to/from selectors until you click on the map or choose a direction.
<img width="1552" alt="Screen Shot 2020-01-29 at 7 20 16 PM" src="https://user-images.githubusercontent.com/728084/73414564-6e544700-42cc-11ea-9370-00fb08a2d56e.png">
