### ISSUE TITLE
Add custom symbols/design for origin/destination stops

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#295]
You can copy what Google maps does (put the red pin marker on the start and end stop, put the name there and bold it) or like put a square for start and triangle for end, or put a checkered flag at the end, or whatever. Just don't use the red/green fills because that clashes with the red/green we use for speeds.

**Comment by exxonvaldez** [comment]
Marking as done.

**Comment by exxonvaldez** [comment]
Fixed by #330.
