### ISSUE TITLE
Include date & time in URL

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#308]
When you customize the date & time in the picker, that information isn't stateful -- it's not captured by the URL. To make sharing easier, it would help to include that information in the URL.

<img width="1552" alt="Screen Shot 2019-09-11 at 9 16 30 PM" src="https://user-images.githubusercontent.com/728084/64753811-722c2c00-d4d9-11e9-984e-05f387c4c41a.png">

For instance, the URL could change from http://muni.opentransit.city/route/12/direction/12___I_F00/fromStop/6879/toStop/4671 to http://muni.opentransit.city/route/12/direction/12___I_F00/fromStop/6879/toStop/4671?date=072219&time=daytime.

@ckrajewski may be interested in taking this on

**Comment by exxonvaldez** [comment]
I need to get some basic form of dates in URLs working for development of #301 and #415 , so I don't have to keep reentering date ranges on page reload.  @ckrajewski 's work on #160 and #347 looks like it shouldn't create any messy conflicts, I'll just add some temporary "stick date state in URL" code to the existing stuff.

**Comment by exxonvaldez** [comment]
This got addressed during a series of PRs around date range support (see above comment), with all of the date settings being encoded in the query string.  Marking as closed.
