### ISSUE TITLE
Create a JSON config file for each city, used by frontend & backend

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#309]
#276 started extracting SF-specific constants into their own file. But @exxonvaldez made a good point: only the frontend could read those constants. The backend would need its own constants. We could make a duplicate city-specific constants file for the backend, but it would probably be cleaner to just make a config JSON file for each city that each frontend & backend could pull from.

**Comment by youngj** [comment]
Implemented in https://github.com/trynmaps/metrics-mvp/pull/409 (but as YAML instead of JSON)
