### ISSUE TITLE
Add padding to routes table

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#339]
Currently the names of the routes are right up against the edge of the routes table. I think some better, more Material-y formatting would help to introduce padding and make them look less like plain ol' blue links.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/728084/66976209-ee280f80-f055-11e9-8557-0524e15c4522.png">

**Comment by exxonvaldez** [comment]
Hmm, I guess this is as far as Material UI default styling goes for tables and links, which is to say, not very.  We can easily remove the `Paper` component that surrounds the route table, that removes the grey line and drop shadow surrounding the table, which both seem unnecessary.

As for the link styling, I'm not sure what you have in mind.  Like, remove the underline and go with some other color such as the palette primary color (matching the blue of the buttons and navbar)?


![Screen Shot 2019-10-22 at 11 05 24 PM](https://user-images.githubusercontent.com/44861283/67362722-77d95080-f520-11e9-936b-44baf56c5dc1.png)

**Comment by exxonvaldez** [comment]
PR created, see above.

![Screen Shot 2019-10-22 at 11 28 23 PM](https://user-images.githubusercontent.com/44861283/67364244-04394280-f524-11e9-8251-330434a78fbb.png)
