### ISSUE TITLE
Mention "travel" time in trip length cards

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#345]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/728084/66977290-3cd7a880-f05a-11e9-912e-9e4ce66c28a6.png">

It should say "13 min wait + 34 min *travel*", or something, instead of just "13 min wait + 34 min", because the second bit isn't clear otherwise. Both cards should add the word "Travel" or "on board."

**Comment by adel-a** [comment]
I want to work on this.

**Comment by bmblumenfeld** [comment]
@hathix I believe this is stale. Any objections if I close?

**Comment by hathix** [comment]
Good catch. I'll close.
