### ISSUE TITLE
procfile issues

### ISSUE THREAD

**Issue by mjrerle2** [trynmaps/metrics-mvp#35]
i noticed a few things with the procfile and at first glance there might be some bugs introduced here

the app is running on a flask dev server serving the static files - maybe we can use nginx to do this for us? we can also feed heroku nginx configs to fine tune the location rules. also, we can choose ports to listen on etc.

npm start: i don't know if this is ideal on a production server. i could be mistaken but isn't this script used for development? as in part of your workflow: change a file and the hot reload job reflects the change. an alternative could be to npm build -> let the web server know where the files are hosted (i think like /app/www/<static_folder>)

**Comment by hathix** [comment]
Hm, yeah, I was encountering problems like this as well. I finally got the site building & running locally but Heroku's configuration is still wrong. Let's talk about it on Wednesday?

My hunch is that we can just run `yarn build` to get the react files built and stored in a static folder, which flask can then serve. As for flask, I think there might be a way to create a prod server with the normal flask CLI.

**Comment by youngj** [comment]
Now using heroku.yml instead of Procfile on Heroku, and using gunicorn as a production server instead of flask. Flask serves the precompiled frontend assets from a static folder, without running npm/react-scripts.
