### ISSUE TITLE
Fix Header Layout in Mobile

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#379]
The header should have full width columns in mobile view, such that the breadcrumbs stack above the date range picker

![image](https://user-images.githubusercontent.com/40367955/68266773-f6e08580-0004-11ea-80b3-bfeebfc2edc6.png)

**Comment by exxonvaldez** [comment]
Fixed this in #415 by moving most of the bread crumb below the blue app bar into its own Paper.  This will also make room in the app bar for a second date picker for date range comparisons (#321).  Still waiting to see if Chris makes updates on #347 , it'll need to be updated to reflect the new layout of bread crumbs.

![Screen Shot 2019-11-26 at 12 06 29 AM](https://user-images.githubusercontent.com/44861283/69611299-55849800-0fe2-11ea-9b8d-6fcf33ccc5a1.png)
