### ISSUE TITLE
Loading indicator while the app pulls data

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#387]
When selecting a route and selecting tops X to Y there is a significant delay while the app pulls data from the bucket and that varies based on a user's bandwidth. For my laptop it took between 3-4 seconds without any indication that it was performing this process which isn't great for a UX perspective.

**Comment by exxonvaldez** [comment]
Also would be worthwhile to do some profiling.  I suspect that moving the Marey chart to its own tab and also deferring the load and rendering of its data will help with performance. #375

**Comment by exxonvaldez** [comment]
Okay, I think this one can be closed now.  #432 covers profiling.  The Marey Chart is now on its own tab and loaded lazily.  And there is an indeterminate circular loading indicator to the left of the date picker via #411 .
