### ISSUE TITLE
Set a <h1> tag for the route after selection

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#391]
We should have an `<h1>` tag at the top of the information frame, but underneath the navigation component for better user experience and SEO

**Comment by exxonvaldez** [comment]
I checked our site using the Google Search Console and using Google Search itself.  Google is already finding the route name on each route's page, but there is no other indexed text.  I also think an H1 would be redundant with the new breadcrumbs that @ckrajewski is working on.  Can you split this into two issues, one for SEO, and one that better describes the UX issue you're seeing (as opposed to just specifying a solution)?

![Screen Shot 2019-11-18 at 12 53 51 PM](https://user-images.githubusercontent.com/44861283/69093051-8a9d5300-0a02-11ea-840a-e4765c3d97f3.png)

**Comment by exxonvaldez** [comment]
Additional thoughts on UX:  One option is to move the breadcrumb entirely out of the blue app bar, and put it just under the app bar.  This would also help with #379 .

A second option is to split the bread crumb, putting only agency in the app bar, or only route (removing the agency breadcrumb and replacing with a different way to get to the home page, such as a back arrow button).  The rest of the bread crumb would go below the app bar.

**Comment by akgupta89** [comment]
So the reason we should have a `<h1>` tag and not rely on breadcrumbs is one `<h1>` is great for any kind of machine processing given that there is only one `<h1>` tag and it defines what is being looked at which is good for SEO and also humans. 

If I was linked to a route page by a friend, I would only have two options to figure out what I'm seeing at first glance. Either I look at the title (not implemented) and determine what I'm looking at, or I look at the breadcrumbs and discern I'm looking at a route. Either way, those aren't ideal, breadcrumbs are for navigation, and not for figuring out what you're looking at. The ideal user experience would be reading the biggest boldest block of text that says "SFMTA Route 38R Summary" and be able to instantly recognize that the related information is attributed to this, and then using the breadcrumbs to navigate away to a more pertinent route should they be interested in looking at that.
