### ISSUE TITLE
Provide descriptions of what each measurement means

### ISSUE THREAD

**Issue by amadigan** [trynmaps/metrics-mvp#392]
In the Routes table we have:

- Name
- Score
- Wait (min)
- 20 min wait %
- Speed (mph)
- Extra Travel (min)

I can kind of guess what some of these mean, but "Extra Travel" for instance, is baffling. We should provide descriptions of what each column means and make it available through something like a tooltip.

**Comment by exxonvaldez** [comment]
#417 addressed this issue somewhat.  There is now one info icon by the "Routes" table title that provides definitions of all the columns.  @amadigan and @hathix is this sufficient to close this issue, or should we do info icons or hover tool tips on the column headers?

**Comment by exxonvaldez** [comment]
Going to close this for now.
