### ISSUE TITLE
Map fixed when scrolling down the routes list

### ISSUE THREAD

**Issue by zachzwy** [trynmaps/metrics-mvp#394]
Please see issue #406 for more information.

Currently on the dashboard page, when you scroll down the routes list, the map will be "scrolled up" and you will see blank on the left. It would be great if the map is sticky there.

<img width="845" alt="Screen Shot 2019-11-06 at 7 01 20 PM" src="https://user-images.githubusercontent.com/22914663/68356693-d7f6f780-00c7-11ea-8a19-2ea04bfe506d.png">

**Comment by SeannyPhoenix** [comment]
This happens on all version of the Dashboard page.

![image](https://user-images.githubusercontent.com/12836949/68357121-2c4ea700-00c9-11ea-9e35-10aedef3d823.png)

**Comment by zachzwy** [comment]
Yeah, I thought it would be great if the map is sticky there. So that we might want to interact with the map later on.
