### ISSUE TITLE
Keep the "Clear Map" button on the route screen

### ISSUE THREAD

**Issue by wllgrnt** [trynmaps/metrics-mvp#399]
Once you've clicked on a route, it's quite difficult to get back to the original map, making misclicks pretty costly.

I think #160 will make this less of an issue, but I still think the "Clear Map" button has value when you've chosen a route.

**Comment by hathix** [comment]
Agree. I might call it "Back" or "Back to Dashboard" or something though.

**Comment by hathix** [comment]
So we tried adding a "return to dashboard" button on the map in #469 and didn't like it. We'd prefer to have a back button on the top left. Look at Google photos for inspiration -- there's a hamburger menu that turns into a back button when you drill down. Let's do this -- have our hamburger menu turn into a back button on any drilled-down views.

![Screen Shot 2020-01-15 at 6 58 43 PM](https://user-images.githubusercontent.com/728084/72489502-1a743900-37c9-11ea-90a0-0f49a78c6615.png)

**Comment by melismae** [comment]
@hathix Sounds good - a button that says "back" or an arrow?

I had explored using the navigation in Material UI to wrap those in the Breadcrumbs component too, just in case this might work:
![Screen Shot 2020-01-15 at 7 55 21 PM](https://user-images.githubusercontent.com/7612577/72492153-16e4b000-37d1-11ea-928e-de50fa0bfe6e.png)

**Comment by exxonvaldez** [comment]
Left arrow from Google Photos looks like this (replaces the hamburger button):

<img width="120" alt="Screen Shot 2020-01-15 at 8 01 25 PM" src="https://user-images.githubusercontent.com/44861283/72492393-e5201900-37d1-11ea-86f1-dd6122321781.png">
