### ISSUE TITLE
Fix inconsistency between route stats & marey chart when no data

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#400]
<img width="1552" alt="Screen Shot 2019-11-06 at 7 05 09 PM" src="https://user-images.githubusercontent.com/728084/68356878-666b7900-00c8-11ea-8807-d6c34cfc7894.png">

Go to a trip with no data logged, and you'll see the expected gray cards with no stats (the NaN is weird, btw), but you'll also see a Marey chart that shows a bunch of runs. I'm not sure whether the Marey chart or the stats are wrong, but there's an inconsistency here... let's figure out what's the matter.

**Comment by exxonvaldez** [comment]
It's probably left over data from a previous load.  We just need something to explicitly clear the Marey chart data.
