### ISSUE TITLE
Path class does not update URL correctly

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#408]
In ControlPanel.jsx, the following code in onSelectFirstStop does not add the "from" stop to the URL if secondStopId is already set:

```
    const path = new Path();
    path.buildPath(FROM_STOP, stopId);

    if (secondStopId) {
      path.buildPath(TO_STOP, secondStopId);
    }

    path.commitPath();
```

It seems like the Path class in routeUtil.js is a fragile and limited way of updating paths since it requires all path parameters (like route ids) to be preceded by a static path token like /route/. It doesn't allow adding parameters that are not preceded by static path tokens like /muni/1/0/2234/3332 . It would also fail if the static token like "route" was itself the value of a path parameter.

routesMap.js already defines the template string ROUTESCREEN.path so there should be an easy way to construct paths from this by passing in the parameters (perhaps there is a function in Redux first router to do this?)

This approach would allow simplifying the code by removing the Path class entirely, add more flexibility in how paths can be structured, and avoid bugs.

**Comment by exxonvaldez** [comment]
See my comment on above PR for proposed fix.  I think it’s best to fix in #347 since that PR depends on the fix, but it could also done first separately if coordinated with @ckrajewski .

**Comment by exxonvaldez** [comment]
Marking this as Chris' issue, as he returned after an absence of a few weeks absence and is working on using actionToPath.

**Comment by youngj** [comment]
@ckrajewski have you started working on this? Otherwise I could work on this now.
