### ISSUE TITLE
If there is no data for a line in the route table, do not display it.

### ISSUE THREAD

**Issue by SeannyPhoenix** [trynmaps/metrics-mvp#413]
The route table on the dashboard displays all routes, regardless if they have data or not. These routes should not display by default. Perhaps add a filter option to include them. (See https://github.com/trynmaps/metrics-mvp/issues/395)

![image](https://user-images.githubusercontent.com/12836949/68826497-0c802b80-0653-11ea-94ec-ddb055ee6ed8.png)

**Comment by hathix** [comment]
I think it helps to show empty rows, since that makes it clear that we normally track those routes. But I agree we could let people filter those out.
