### ISSUE TITLE
Avoid running out of memory when fetching vehicle location data for large agencies

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#423]
When running compute_arrivals.py or get_state.py, vehicle location data is loaded from tryn-api in chunks (e.g. 15 minutes at a time) in order to prevent the tryn-api server from running out of memory. 

However, the local Python process keeps all of the loaded chunks in memory at once until all chunks are fetched, before splitting the data by route and writing the day's worth of data to disk for each route. For transit agencies with a lot of vehicles, such as TTC (agency id: ttc), it is possible that the Python process may be killed due to running out of memory before writing the vehicle location data to disk.

One way to avoid this would be to write each chunk to the backend/data directory after it is fetched, instead of keeping them all in memory. 

This could also be used as a cache to avoid fetching identical chunks from tryn-api again if running compute_arrivals.py or get_state.py multiple times.

However it would still be necessary to load data from all chunks in order to save 1 day's worth of data for a particular route, which could also lead to running out of memory. To avoid this, chunks could be split by route before saving on disk.

The relevant code is in the get_state function in backend/models/trynapi.py .

**Comment by EddyIonescu** [comment]
https://github.com/trynmaps/metrics-mvp/pull/580
