### ISSUE TITLE
Handle loops correctly when displaying list of stops in the UI

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#426]
The Portland Streetcar A Loop and B Loop lines travel in a continuous loop. However, each line has an arbitrary beginning/end stop (which are identical). Currently, the UI only allows selecting a destination stop that appears after the origin stop in the list of stops. 

If the beginning/end stop for a direction are identical, the UI should consider the route to be a loop, and should add the stops that are after the arbitrary beginning/end stop and before the origin stop to the bottom of the destination stop dropdown list.

In addition to the UI change, this will also need backend support at https://github.com/trynmaps/metrics-mvp/issues/425 in order for the statistics to be calculated correctly.

**Comment by licarpen** [comment]
What is the OPENTRANSIT_AGENCY_IDS for Portland street cars?

**Comment by youngj** [comment]
It's `portland-sc`. The available agency IDs are part of the file names in backend/agencies/ .

**Comment by licarpen** [comment]
Frontend aspect of this issues appears resolved.  Street car lists are now rendering correctly and original functionality is preserved for non-loop routes.
