### ISSUE TITLE
Fix weird line spacing on stats tiles

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#436]
The line spacing on the tiles (see "Typical Journey") is pretty wide, making the tile look weird when the text wraps. Can we reduce that?

![Screen Shot 2019-11-20 at 8 00 51 PM](https://user-images.githubusercontent.com/728084/69303402-b91d5880-0bd1-11ea-8416-8a11b34b70f9.png)

**Comment by exxonvaldez** [comment]
Marking as up for grabs per Mason.

**Comment by hathix** [comment]
Terence's new UI (with wider tiles) should remove this problem
