### ISSUE TITLE
Fix "infinite" speed appearing

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#439]
For some reason, sometimes the speed is shown as infinite. 

![Screen Shot 2019-11-20 at 8 29 52 PM](https://user-images.githubusercontent.com/728084/69304161-8e80cf00-0bd4-11ea-8e6a-ece28ec27b11.png)

It might be caused by having just 1 stop in the dataset:

![Screen Shot 2019-11-20 at 8 31 11 PM](https://user-images.githubusercontent.com/728084/69304237-c425b800-0bd4-11ea-89cb-3d3c5dcf5bbe.png)

**Comment by exxonvaldez** [comment]
Looks like the E and F effectively have a new temporary terminal at Beach & Stockton.  I can update the muni.yaml file to mark this as the first stop.  Looks like muni.yaml needs some other updates also now that we've changed to gtfs stop ids from nextbus stop ids.

https://www.sfmta.com/travel-updates/e-and-f-streetcars-turn-back-pier-39-starting-october-21-2019

![north_beach_shuttle_loop_map](https://user-images.githubusercontent.com/44861283/69682862-b4d8bb80-1067-11ea-9f06-e598ab428d39.png)


> E and F Streetcars Turn Back at Pier 39 Starting October 21, 2019
> Monday, October 21, 2019 - 5:00am
> Route(s) Affected
> E Embarcadero
> F Market & Wharves
> Service Affected
> Accessibility
> Transit
> 
> Map of E/F shuttle loop to Fisherman's Wharf
> 
> Starting October 21 and continuing for approximately one year, San Francisco Public Works will be constructing Phase II of the Jefferson Streetscape Improvement Project. To accommodate this work, the E Embarcadero and F Market & Wharves historic streetcars will turn back at Pier 39. A shuttle bus will operate in a loop to serve missed stops near Fisherman’s Wharf.
> 
> The last streetcar stop toward Fisherman’s Wharf will be at Embarcadero & Stockton (Pier 39).
> A new temporary streetcar stop will be at Beach & Stockton, southeast corner. This temporary stop does not have a wheelchair ramp.
> A bus shuttle will operate in a loop to serve missed stops on Jefferson and Beach streets:
> Transfer between shuttle and streetcar at Pier 39 or at Embarcadero & Bay. Both of these stops have wheelchair ramps.
> 
> Phase II of the Jefferson Streetscape Improvement Project includes the installation of widened sidewalks, pedestrian scale lights, bike parking, landscaping, trees, and public seating on Jefferson Street from Jones to Powell Street. For more information on the project, visit the Jefferson Streetscape Project page.
