### ISSUE TITLE
Raise exception for get_value in resolve_median

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#455]
_Originally posted by @youngj in https://github.com/trynmaps/metrics-mvp/pull/372_

**Comment by hathix** [comment]
<img width="678" alt="Screen Shot 2019-11-24 at 6 11 55 PM" src="https://user-images.githubusercontent.com/728084/69503274-eb86c880-0ee5-11ea-8cab-3ece571c4992.png">

**Comment by Brian-Lee** [comment]
Would this do the trick?:

        if wait_time_median.get_value(parent["route_metrics"].route_id, parent["direction_id"], parent["start_stop_id"]) is None:
            raise Exception(f"There is no cached median value returned for start_stop_id {parent['start_stop_id']} at times {parent['start_time'], parent['end_time']}.")
