### ISSUE TITLE
"Last 30 days" may have off by one error

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#499]
This seems to show just 29 days (12/9 - 1/7)?

![Screen Shot 2020-01-08 at 7 51 32 PM](https://user-images.githubusercontent.com/728084/72036638-4be08800-3250-11ea-867c-c2adad0c62e0.png)

**Comment by Brian-Lee** [comment]
When I count the days, I get 30:
12/09, 12/10, 12/11, 12/12, 12/13, 12/14, 12/15, 12/16, 12/17, 12/18, 
12/19, 12/20, 12/21, 12/22, 12/23, 12/24, 12/25, 12/26, 12/27, 12/28, 
12/29, 12/30, 12/31, 01/01, 01/02, 01/03, 01/04, 01/05, 01/06, 01/07

Am I wrong?

**Comment by exxonvaldez** [comment]
Looks like 30 days to me.
