### ISSUE TITLE
Update color scheme

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#534]
Sonal created a new logo: https://docs.google.com/presentation/d/1gyU3UF-BIwFyw6WqwFKlEO7Pt26yPDYzOKvsD-pBwwU/edit?usp=sharing.

We should use this logo on the app: menu bar at the top should ideally have the logo, and any general items should use the hex codes (#0177BF or #D02143).

**Comment by hathix** [comment]
wed probably want to do this via material theme customization https://material-ui.com/customization/palette/

**Comment by hathix** [comment]
terence: "I can add the logo to the app later this week, unless someone else wants to.  We might have to change the color of the blue app bar at the top of the page to white or some lighter color, and the breadcrumb bar below it from white to some other color."

terence: "We are using the material UI color palette for our maps and charts, if you want shades that won’t clash with those: https://material-ui.com/customization/color/"

**Comment by sonalsomaiya** [comment]
Could we use this color palette for everything but blue and red to use the hex codes above?

**Comment by hathix** [comment]
There was more conversation on slack so ill just link it here https://sfbrigade.slack.com/archives/C7HUYBHAA/p1580964413032800

**Comment by hathix** [comment]
You can use the `createMuiTheme()`

https://material-ui.com/customization/color/#color-tool

![image](https://user-images.githubusercontent.com/728084/73907784-724c1000-485c-11ea-8b4d-cf22e4d6a28d.png)

**Comment by exxonvaldez** [comment]
#538 applied a Material UI theme with a custom primary and secondary colors generated via the tool.  Marking as closed.
