### ISSUE TITLE
Use new logo throughout site

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#535]
Sonal made a new logo, lets get it everywhere: 

https://docs.google.com/presentation/d/1gyU3UF-BIwFyw6WqwFKlEO7Pt26yPDYzOKvsD-pBwwU/edit?usp=sharing

**Comment by hathix** [comment]
![Open transit (1)](https://user-images.githubusercontent.com/728084/73907285-93136600-485a-11ea-8d15-66e7d5b751a9.png)

**Comment by hathix** [comment]
Dont forget to update favicon. i asked sonal for a special version for that 16x16 size

**Comment by hathix** [comment]
for favicon you can use this, just crop it right
![Open transit no text](https://user-images.githubusercontent.com/728084/73907870-bdfeb980-485c-11ea-9643-d95924ce17ef.png)

**Comment by exxonvaldez** [comment]
I think this issue is basically done, unless we've forgotten something.  #557 should include another iteration of the logo but that can be tracked there.
