### ISSUE TITLE
Duplicate Muni routes

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/metrics-mvp#581]
Muni’s current GTFS file contains each route twice, but with a different route ID. This is because, looking at the service_id, one is for before February 22, and one is for once it occurs. Note that February 22 was the rollout date of their most recent service changes, which were moving the 1AX/BX last trip time earlier and adding early-morning Muni Metro bus routes, in addition to the existing OWL service.

**Comment by hathix** [comment]
#127 looks similar to this.
