### ISSUE TITLE
Date range comparison UI improvements

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#582]
Jesse [said](https://github.com/trynmaps/metrics-mvp/pull/461#issuecomment-586020958) on #461:

> 
> I don't think cards are an effective way of comparing two sets of metrics. Visually it appears haphazard because each statistic is aligned somewhat differently and the two ranges have different font sizes. Also, the cards don't make it very clear which statistic refers to which date range (you have to refer to the ranges shown in the visually disconnected top right corner of the screen). Clarifying this within the card UI would require additional redundant text in each card.
> 
> The same issues would apply when using cards to compare actual/scheduled metrics within a single date range.
> 
> Copied from #549:
> 
> It seems like a more straightforward approach would be to use a table where each row is a statistic, with columns for the first date range, the second date range, and percentage increase/decrease 
> 
> For example:
> 
> |  | 1/1/2020  | 2/1/2020 | % Change | |
> | --- | --- | --- | --- | --- |
> | Median Service Frequency |  5 min |  8 min | +60% | `__________0******____` | 
> | Median Trip Time |  10 min |  8 min | -20% | `________**0__________` |
> 
> (The last column shows an optional horizontal bar to visually represent the % change.)
> 
> Another approach would be could be a bar graph with series like Median Service Frequency, Median Trip Time, etc. where each series has two side by side bars for each date range.
> 
> Both of these UI approaches would also work for comparing Actual vs Scheduled statistics for a single date range.
> 
> The date ranges should also be labeled in the various charts.
> 
> In the histograms, the bars from the top histogram often block the view of the bottom histogram. The bars should probably be displayed side by side instead of overlaid.

**Comment by exxonvaldez** [comment]
I'm working on a solution that is modeled on the Google Analytics UI.  That being said, it would still be helpful to have a text grid like this available for printing and exporting.
