### ISSUE TITLE
Let users see all routes on homepage's spider map

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#590]
Currently, there's no way to see all routes on the homepage's spider map. You can only click in certain areas and see the nearby routes.

<img width="1552" alt="Screen Shot 2020-02-27 at 6 48 00 AM" src="https://user-images.githubusercontent.com/728084/75501151-f9843380-5983-11ea-8186-9cb2d965267e.png">

We should either (1) change the behavior such that the map shows all routes when no point on the map is clicked, or (2) add a "show all routes" button to the bottom of the map near the "clear" button.

I prefer (1) because:

* It makes the homepage more engaging by letting new users see all the routes as soon as they open the app. Currently it looks bland, since all you see on the left is a gray map.
* It makes the spider map / table behavior more consistent. When you click on a spot on the map, the table shows just the routes that are visible on the spider map. But when you haven't clicked, the table shows all routes while the map shows no routes. That's inconsistent.
* It avoids adding yet another button to the map.

However, (2) avoids putting a lot of information in front of new users.

A compromise could be to only show the most common routes on the map by default, but that would make the map-table behavior even more inconsistent.

**Comment by exxonvaldez** [comment]
I also like your suggestion from #189 where we start with a default pin, presumably near Market Street so as to include a large number of popular routes.  We should test out the performance and usability of showing all routes on the map to see how viable that is.

**Comment by hathix** [comment]
Putting a default pin downtown is a good idea, now that you remind me of it - unlike my two previous suggestions, that approach also teaches users that they can click on the map to filter routes. That mechanic is hidden right now.
