### ISSUE TITLE
Show overlapping routes on spider map

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#591]
Routes like the N, KT, and E overlap for parts of their service, but our spider map only lets you see one. Is there a way to show the routes "hidden" underneath other routes?

![image](https://user-images.githubusercontent.com/728084/75455135-b3e84c00-592c-11ea-9321-1a75866dadc0.png)

**Comment by exxonvaldez** [comment]
This is a tough one to solve algorithmically, but it's in the realm of possibility.  I think on most transit maps, adjustments to prevent overlapping are done manually/custom, or only one route is displayed at a time.

I looked into it and found a Leaflet plugin that will "offset" a line by a given amount:  https://github.com/bbecquet/Leaflet.PolylineOffset .  This still requires us to determine which lines overlap and how much each line should be offset by.  Plus offsetting only makes sense where the lines actually overlap.

**Comment by hathix** [comment]
In the interest of scalability, I think it's better to not manually adjust lines or track which lines overlap. One alternative solution could be to make all the lines semi-transparent so you can at least see that there are routes below.

**Comment by exxonvaldez** [comment]
They actually are semi-transparent (50% opacity), but it actually doesn't help too much with overlapping segments (crossing segments are ok).

**Comment by hathix** [comment]
Looks like there's not much we can do here then. Hopefully route hovering will be enough to show users that there are multiple routes there.
