### ISSUE TITLE
Figure out "by day" tab when comparing date ranges.

### ISSUE THREAD

**Issue by exxonvaldez** [trynmaps/metrics-mvp#592]
@hathix wrote:

You're right that this is tricky. My first guess is to use the same axis for both, but make the lines different length (so the shorter interval ends earlier). We can iterate on this later though, once we get the big items done.

_Originally posted by @hathix in https://github.com/trynmaps/metrics-mvp/pull/589_

**Comment by hathix** [comment]
Do you have any other ideas for the ux here? I haven't been able to think of another elegant one besides just having the two lines overlaid and making one longer

**Comment by exxonvaldez** [comment]
That's what Google Analytics does, so I'm planning to copy them in my #461 followup PR.   Going to mark this as closed since it seems pretty workable.
