### ISSUE TITLE
Add support for more Nextbus-served transit systems

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#601]
This is the full list of transit systems that Nextbus supports: http://webservices.nextbus.com/service/publicXMLFeed?command=agencyList.

These are the easiest ones to add support for, so we should pull in more. Specifically I think we should add ones for LA's metro & Seattle streetcar since those are the other most prominent lines that use Nextbus.

**Comment by hathix** [comment]
TTC, Muni, and Portland Streetcar all use Nextbus. Trimet doesn't but seems to have its own GTFS realtime feed: https://developer.trimet.org/GTFS.shtml. Adding other Nextbus-supported agencies would be an easiest first step, regardless

**Comment by EddyIonescu** [comment]
So thanks to the work Jesse's done there's no longer any advantage to using a Nextbus vs. a GTFS-RT agency, so this issue doesn't seem very relevant.

Also LA Metro has a huge bus network (2nd largest in North America) so cost might also be an issue. Personally, I'm looking to add in agencies from the Toronto area then from the rest of the Bay Area.
