### ISSUE TITLE
Setup python based cron job system

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#604]
Since we already have a GCP app instance running 24/7, it makes operational and financial sense to piggyback on the existing server instance to run cron scripts on demands.

We'll need something like this: https://stackoverflow.com/questions/21214270/scheduling-a-function-to-run-every-hour-on-flask

Ideally the cronjob list would be loaded from a JSON array stored in a separate file and either execute a cli command e.g. "node daily_message.js" or make a GET request to a URL e.g. `http://muni.opentransit.city/api/post_tweet`.

**Comment by youngj** [comment]
Kubernetes already has a cron job system, so it's not necessary to create a new one. See for example kubernetes/compute-new-cronjob.yaml and kubernetes/save-routes-cronjob.yaml
