### ISSUE TITLE
With date ranges, page too wide on mobile

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#620]
![Screenshot_20200329-195709](https://user-images.githubusercontent.com/728084/77864594-86c2de00-71f7-11ea-9408-18e7f1ec21e2.png)

On my phone, the header bar is so wide that the page has to scroll horizontally - it can't all fit on the phone screen at once. that's not good ui.

**Comment by youngj** [comment]
This was noted in https://docs.google.com/document/d/1RpVZsbBHFiPLXbKcmsa4gi68ab-C_yi1Ar3lHshu6i4/edit#heading=h.huqeezk0uz7i and addressed in #607.
