### ISSUE TITLE
Isochrone LatLng error

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#623]
Loaded the isochrone and got this. Was it because I didn't give my geolocation or something?

<img width="1189" alt="Screen Shot 2020-04-01 at 9 52 01 PM" src="https://user-images.githubusercontent.com/728084/78202843-5e3f1c00-7463-11ea-9979-79663db60d4d.png">

**Comment by youngj** [comment]
Fixed in #607, to avoid trying to generate isochrones on page load when the user's geolocation is not available and defaultIsochroneCenter is not defined in the agency config.
