### ISSUE TITLE
Frontend doesn't load when serving from backend

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/metrics-mvp#663]
The changes made to support the static build caused an error to be thrown when loading the frontend from the application ```Uncaught SyntaxError: Unexpected token '<'```

This breaks our Heroku deployments (eg. https://eddy-opentransit.herokuapp.com/) as those use the application to serve the frontend.

**Comment by EddyIonescu** [comment]
@akgupta89 just wondering did you have any ideas for this? Otherwise I'll look into investigating it.

**Comment by hathix** [comment]
I think this is the same as #651: an HTML file is being sent as JavaScript, and JavaScript sees a "<" to open a tag and freaks out.

**Comment by EddyIonescu** [comment]
https://github.com/trynmaps/metrics-mvp/pull/664
