### ISSUE TITLE
Show wait time and travel time across different parts (am rush/midday/pm rush) of the day

### ISSUE THREAD

**Issue by exxonvaldez** [trynmaps/metrics-mvp#81]
The mockup shows a bar chart (and the same data in a line chart with time of day on the x axis) of how wait time and travel time vary across different parts (am rush/midday/pm rush, etc.) of a day.  Since we're currently showing data for one time range of one day, the next incremental step is to make a chart of multiple time ranges for one day.  It is a slightly different workflow from what we have now, though, so we may need UI design changes to support this.

**Comment by hathix** [comment]
can you write up what data you want to input and get out from the backend? then we can build out a backend API to fulfill that.

**Comment by hathix** [comment]
![IMG_20190501_194223](https://user-images.githubusercontent.com/728084/57054429-700fb200-6c49-11e9-944d-9e10ecdbb01c.jpg)

**Comment by exxonvaldez** [comment]
Loose API writeup at:  https://docs.google.com/document/d/10O2Pf61iiSOtrXV-x_6HPAJztXkfT7-zBYxJB5LnUYk/edit?usp=sharing

**Comment by exxonvaldez** [comment]
Marking issue as closed now that we have this chart and API merged in.
