### ISSUE TITLE
some stops on nextbus have no direction

### ISSUE THREAD

**Issue by jtanquil** [trynmaps/metrics-mvp#84]
When pulling stop information for a route from nextbus, there will sometimes be stops with no associated direction. For example, on route KT, stop 7058 has no associated direction:

http://webservices.nextbus.com/service/publicJSONFeed?command=routeConfig&a=sf-muni&r=KT&t=0&terse

Searching for 7058 finds the stop info (name, lat/lon, etc) for stop 7058 and 17058 (the same stop, but for different directions) but those stops don't show up in the list of stops for each direction. This will happen for stops with only one direction as well - stop 4509 on route L is an example:

http://webservices.nextbus.com/service/publicJSONFeed?command=routeConfig&a=sf-muni&r=L&t=0&terse

I don't know the exact number of stops where this happens, but I'd estimate that 30% of routes have at least one stop with no associated direction; I can find the exact number later.

**Comment by hathix** [comment]
We were thinking you could use the previous/next stop to guess which direction the route is. For instance, suppose we guess that stop X is inbound. Then we look at the timestamps for stop X and stops X-1 and X+1 (where smaller numbers are closer to downtown). If the time for X-1 < time for X < time for X+1, we're right - it's inbound.

Not sure how scalable this is though.

**Comment by jtanquil** [comment]
Here's a list of stops with no direction: 
![image](https://user-images.githubusercontent.com/18497540/57054392-35a61500-6c49-11e9-983a-1682c2cafc8e.png)
