### ISSUE TITLE
react-d3-components has issues

### ISSUE THREAD

**Issue by exxonvaldez** [trynmaps/metrics-mvp#90]
Same chart in React-Vis vs react-d3-components, trying to match NYC bus stats as closely as possible just as a test:

![Screen Shot 2019-05-08 at 4 12 15 PM](https://user-images.githubusercontent.com/44861283/57414379-b797c000-71ac-11e9-8b49-b690c74ad4b0.png)
In creating a new "phases of the day" chart, I came across these issues with react-d3-components:

* Tooltips when hovering over charts do not work.
  * Possibly due to conflict with react-bootstrap CSS.
  * Could not find a good fix, seems hard to override third party packages.
* Documentation is not available, but there are good set of examples.
* Customization options are limited.
  * Example: cannot remove axis lines.
  * The original (non-React) D3 API allows clients to remove and modify svg elements it creates, but here we cannot do that.
* No built in support for chart legends.
* Last pull request merged June 2018, project is looking for maintainers.

I looked for articles about popular React charting packages:

* https://medium.com/dailyjs/data-visualization-libraries-for-react-developers-in-2019-a2b9c01262f8
  * (Victory, React-Vis by Uber)
* http://voidcanvas.com/top-10-react-graph-chart-libraries-with-demo/
  * (ReCharts, Victory, VX, React-Vis, Nivo, ChartJS, Rumble, highCharts, Easy Chart, fusionCharts)
* https://www.overloop.io/blog/top-5-react-chart-libraries
  * (Nivo, React-vis, Victory, ReCharts, ChartJS)

Of these, React-Vis looked good visually. It offered more customization options (and correspondingly more complex component hierarchy). It uses D3-inspired scales.

I tried reimplementing a chart in React-Vis.  Worked pretty well.  Issues:

* Documentation is sometimes out of date.
* Link to view source of examples is sometimes missing.
* ~~Some bugs.  For example, height of legend lines is not actually settable due to some hardcoded css.~~ My mistake, included wrong version of react-vis css file.

**Comment by exxonvaldez** [comment]
![Screen Shot 2019-05-08 at 4 12 15 PM](https://user-images.githubusercontent.com/44861283/57414364-acdd2b00-71ac-11e9-93e1-0afbff763c26.png)

**Comment by hathix** [comment]
NYC BusStats uses Plot.ly; there's [a plugin to make Plot.ly work with React](https://plot.ly/javascript/react/) so we could use that later if we want.

**Comment by hathix** [comment]
But for now I think using react-vis is better

**Comment by exxonvaldez** [comment]
![Screen Shot 2019-05-30 at 3 28 56 AM](https://user-images.githubusercontent.com/44861283/58627044-196ab780-828b-11e9-94a4-bcad0f31076e.png)
![Screen Shot 2019-05-30 at 3 29 49 AM](https://user-images.githubusercontent.com/44861283/58627104-415a1b00-828b-11e9-959e-f7b3b190297b.png)

The react-vis charts now have fixed dimensions so the page doesn't get super wide for unusual histograms.  They look better and are easier to read in most situations.

**Comment by exxonvaldez** [comment]
Eddy also suggested Plotly.  He has had a good experience with it.  I looked at the docs, it seems like it can do a lot more than react-vis.  Can revisit when we add more charts or when we get a high fidelity UI design.

**Comment by exxonvaldez** [comment]
Marking issue as closed now that react-d3-components is no longer in master,
